// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tddrdklnysrtwvtbpfvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZHJka2xueXNydHd2dGJwZnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDA3MjEsImV4cCI6MjA2MjM3NjcyMX0.d6fxUXQHZWD2ujOQyB9HiQt8KuZIc4IdXmI1ClBIvWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);